import { describe, expect, it } from 'vitest'
import { archimedesController as controller, readingsFor, type ArchimedesState } from './controller'
import { createLabRuntime, reduceLabAction } from '../../runtime/reducer'

function act(state: ArchimedesState, type: string, payload?: unknown) {
  return controller.reduce(state, { type, payload }).state
}
function move(state: ArchimedesState, subject: string, x: number, y: number) {
  return act(state, 'move', { subject, position: { x, y } })
}
function hang(state: ArchimedesState, subject: 'object' | 'bucket') {
  const meter = state.positions.meter
  return move(state, subject, meter.x, meter.y + (subject === 'object' ? 234 : 275))
}
function weighBaselines() {
  let state = controller.createInitialState()
  state = hang(state, 'bucket')
  state = act(state, 'recordReading')
  state = act(state, 'detach')
  // 断开不再自动归位；称完空桶后显式放回溢水口下接水。
  state = move(state, 'bucket', 363, 378)
  state = hang(state, 'object')
  return act(state, 'recordReading')
}
function immersion(state: ArchimedesState) {
  // 金属块下缘 464，在杯底 484 上方；10 mL 金属块完全浸没。
  return move(state, 'meter', 195, 86)
}
function finish(state: ArchimedesState) {
  state = act(state, 'recordReading')
  state = act(state, 'detach')
  state = move(state, 'meter', 474, 100)
  state = hang(state, 'bucket')
  state = act(state, 'recordReading')
  return act(state, 'recordTrial')
}

describe('阿基米德原理实验的称重与排液', () => {
  it('旧快照四项已记录但未保存时，切换自动记录后仍能保存本组', () => {
    let state = act(hang(controller.createInitialState(), 'object'), 'recordReading')
    state = act(immersion(state), 'recordReading')
    state = act(move(state, 'meter', 474, 100), 'detach')
    state = act(hang(state, 'bucket'), 'recordReading')
    state = act(act(state, 'emptyBucket'), 'recordReading')
    expect(state.trials).toHaveLength(0)
    state = act(controller.restore(controller.snapshot(state)), 'autoMeasure')
    expect(state.trials).toHaveLength(1)
    expect(state.trials[0].valid).toBe(true)
  })
  it.each([['copper', .88, .78], ['iron', .76, .67], ['aluminum', .26, .17]] as const)('%s按四步自动采样并保存本组，重复采样不生成重复组', (material, weight, tension) => {
    let state = hang(act(controller.createInitialState(), 'setObjectSettings', { material, showScale: false, sway: true, wetting: false }), 'object')
    state = act(state, 'autoMeasure')
    expect(state.samples.objectGravity).toBe(weight)
    state = act(immersion(state), 'autoMeasure')
    expect(state.samples.tension).toBe(tension)
    state = act(move(state, 'meter', 474, 100), 'detach')
    state = act(hang(state, 'bucket'), 'autoMeasure')
    expect(state.samples.filledBucketGravity).toBe(.3)
    state = act(state, 'startBucketPour')
    const pouring = controller.reduce(state, { type: 'autoMeasure' })
    expect(pouring.state.samples.bucketGravity).toBeNull()
    for (let i = 0; i < 24; i++) state = act(state, 'advanceBucketPour', .1)
    state = act(state, 'autoMeasure')
    expect(state.samples.bucketGravity).toBe(.2)
    expect(state.trials).toHaveLength(1)
    expect(state.trials[0].valid).toBe(true)
    expect(controller.restore(controller.snapshot(state)).trials).toEqual(state.trials)
    expect(act(state, 'autoMeasure').trials).toHaveLength(1)
    state = act(state, 'newTrial')
    expect(state.samples.objectGravity).toBeNull()
    expect(state.trials).toHaveLength(1)
  })

  it('自动采样不记录部分浸入、碰底、持续运动或超量程的示数', () => {
    let state = hang(controller.createInitialState(), 'object')
    state = move(state, 'meter', 195, -62)
    expect(readingsFor(state).submergedVolume).toBeGreaterThan(0)
    expect(act(state, 'autoMeasure').samples.tension).toBeNull()
    state = move(state, 'meter', 195, 106)
    expect(readingsFor(state).bottomContact).toBe(true)
    expect(act(state, 'autoMeasure').samples.tension).toBeNull()
    state = hang(controller.createInitialState(), 'object')
    expect(act({ ...state, meterSettings: { ...state.meterSettings, speed: 1 } }, 'autoMeasure').samples.objectGravity).toBeNull()
    expect(act({ ...state, meterSettings: { ...state.meterSettings, range: 1 }, objectSettings: { ...state.objectSettings, material: 'copper' }, objectWetVolume: 20 }, 'autoMeasure').samples.objectGravity).toBeNull()
  })

  it('溢水杯刷新只恢复默认水位，杯内物体体积与已有桶水和记录保留', () => {
    let state = move(controller.createInitialState(), 'cup', 220, 180)
    state = { ...state, liquidVolume: 70, collectedVolume: 7 }
    state = act(state, 'resetCup')
    expect(state.positions.cup).toEqual({ x: 220, y: 180 })
    expect(state.liquidVolume).toBe(90)
    expect(state.collectedVolume).toBe(7)
    state = immersion(hang(controller.createInitialState(), 'object'))
    const collected = state.collectedVolume
    state = act({ ...state, liquidVolume: 70 }, 'resetCup')
    expect(state.liquidVolume).toBe(80)
    expect(state.collectedVolume).toBe(collected)
    expect(readingsFor(state).waterY).toBe(295)
  })
  it('杯内木块随恢复的水位上浮，已有桶水不会因补水重复增加', () => {
    let state = controller.createInitialState()
    state = { ...state, liquidVolume: 70, collectedVolume: 6, objectSettings: { ...state.objectSettings, material: 'wood' }, positions: { ...state.positions, object: { x: 195, y: 293.2 } } }
    state = act(state, 'resetCup')
    expect(state.liquidVolume).toBeCloseTo(84)
    expect(state.positions.object.y).toBeCloseTo(263.8)
    expect(readingsFor(state).waterY).toBeCloseTo(295)
    expect(state.collectedVolume).toBe(6)
  })
  it.each(['copper', 'iron', 'aluminum'] as const)('按物体重、液中示数、桶液重、空桶重的顺序完成%s实验', material => {
    let state = act(controller.createInitialState(), 'setObjectSettings', { material, showScale: false, sway: false, wetting: false })
    state = act(hang(state, 'object'), 'recordReading')
    state = act(immersion(state), 'recordReading')
    state = move(state, 'meter', 474, 100)
    state = act(state, 'detach')
    state = act(hang(state, 'bucket'), 'recordReading')
    const filled = state.samples.filledBucketGravity
    state = act(state, 'emptyBucket')
    state = act(state, 'recordReading')
    expect(state.samples.bucketGravity).toBe(.2)
    expect(state.samples.filledBucketGravity).toBe(filled)
    state = act(state, 'recordTrial')
    expect(state.trials[0].valid).toBe(true)
    expect(controller.completion(state).complete).toBe(true)
  })
  it.each(['object', 'bucket'] as const)('将测力计挂钩移到%s吊环也能挂起器材', subject => {
    const state = controller.createInitialState()
    const eyeY = state.positions[subject].y - (subject === 'object' ? 14 : 55)
    const result = move(state, 'meter', state.positions[subject].x, eyeY - 220)
    expect(result.attached).toBe(subject)
    expect(result.positions[subject]).toEqual(state.positions[subject])
    expect(readingsFor(result).force).toBeGreaterThan(0)
  })
  it('测力计侧挂接不能绕过单向锁定，不能移动锁定小桶', () => {
    let state = move(controller.createInitialState(), 'object', 600, 335)
    state = act(state, 'setMeterSettings', { ...state.meterSettings, direction: 'right' })
    state = move(state, 'meter', 600, 100)
    expect(state.attached).toBe(null)
    expect(state.positions.object.y).toBe(335)
    state = act(controller.createInitialState(), 'setBucketLocked', true)
    state = move(state, 'meter', 363, 103)
    expect(state.attached).toBe(null)
  })
  it('端点轨迹只在松手终点挂接，途中经过吊环后移开不会整段回退', () => {
    let state = controller.createInitialState()
    state = act(state, 'setMeterSettings', { ...state.meterSettings, lockMode: 'none' })
    const result = controller.reduce(state, { type: 'pullMeterPath', payload: { endpoint: 'hook', positions: [{ x: 474, y: 401 }, { x: 600, y: 220 }] } })
    expect(result.feedback.outcome).toBe('accepted')
    expect(result.state.attached).toBe(null)
    expect(result.state.positions.meter).toEqual({ x: 600, y: 0 })
    state = act(state, 'pullMeterPath', { endpoint: 'hook', positions: [{ x: 600, y: 220 }, { x: 474, y: 401 }] })
    expect(state.attached).toBe('object')
    expect(state.positions.object.y).toBe(415)
  })
  it('向下锁定的挂接不反向回跳，也不因拖动采样密度不同而变化', () => {
    let state = controller.createInitialState()
    state = act(state, 'setMeterSettings', { ...state.meterSettings, direction: 'down' })
    for (const positions of [[{ x: 474, y: 181 }], [{ x: 474, y: 160 }, { x: 474, y: 181 }]]) {
      const result = act(state, 'movePath', { subject: 'meter', positions })
      expect(result.attached).toBe(null)
      expect(result.positions.meter.y).toBe(181)
    }
  })
  it('通过四次真实称重得到浮力和排液重力，形成可完成的记录', () => {
    const state = finish(immersion(weighBaselines()))
    expect(state.trials).toHaveLength(1)
    expect(state.trials[0].samples).toEqual({ objectGravity: 0.88, bucketGravity: 0.2, tension: 0.78, filledBucketGravity: 0.3 })
    const data = controller.deriveMeasurements(state)
    expect(data.find(m => m.key === 'buoyancy')?.value).toBe(0.1)
    expect(data.find(m => m.key === 'displacedLiquidGravity')?.value).toBe(0.1)
    expect(controller.completion(state).complete).toBe(true)
  })

  it('取出后桶中的水保留；再次浸入同一高度不会凭空再产生排液', () => {
    let state = immersion(weighBaselines())
    expect(state.liquidVolume).toBeCloseTo(80)
    expect(state.collectedVolume).toBeCloseTo(10)
    state = move(state, 'meter', 474, 100)
    expect(readingsFor(state).submergedVolume).toBe(0)
    expect(state.collectedVolume).toBeCloseTo(10)
    state = immersion(state)
    expect(state.collectedVolume).toBeCloseTo(10)
    expect(state.liquidVolume + state.collectedVolume + state.lostVolume).toBeCloseTo(90)
  })

  it('部分浸入连续改变示数和排液；完全浸没后继续下沉浮力不变', () => {
    let state = hang(controller.createInitialState(), 'object')
    state = move(state, 'meter', 195, -46)
    // 水面 y=295，物体下缘 y=332：浸入 37/78，排开约 4.744 mL。
    expect(readingsFor(state).submergedVolume).toBeCloseTo(4.74358974)
    expect(state.collectedVolume).toBeCloseTo(4.74358974)
    state = move(state, 'meter', 195, 34)
    const fullReading = readingsFor(state).force
    state = move(state, 'meter', 195, 84)
    expect(readingsFor(state).force).toBeCloseTo(fullReading)
    expect(state.collectedVolume).toBeCloseTo(10)
  })

  it('水未加满会减少收集量，数据不相等时不会宣布验证成功', () => {
    let state = act(weighBaselines(), 'setWaterVolume', 85)
    state = finish(immersion(state))
    expect(state.collectedVolume).toBeCloseTo(5)
    expect(state.trials[0].valid).toBe(false)
    expect(controller.completion(state).complete).toBe(false)
    expect(controller.report(state).errorAnalysis.join('')).toContain('加满')
  })

  it('接水桶移开时排液记为损失，移回来不会补出已丢失的水', () => {
    let state = move(weighBaselines(), 'bucket', 600, 378)
    state = immersion(state)
    expect(state.collectedVolume).toBe(0)
    expect(state.lostVolume).toBeCloseTo(10)
    state = move(state, 'bucket', 363, 378)
    state = immersion(state)
    expect(state.collectedVolume).toBe(0)
    state = finish(state)
    expect(state.trials[0].valid).toBe(false)
    expect(controller.report(state).errorAnalysis.join('')).toContain('漏接')
  })

  it('物体碰底时不能用测力计读数证明浮力关系', () => {
    const state = finish(move(weighBaselines(), 'meter', 195, 106))
    expect(state.trials[0].valid).toBe(false)
    expect(controller.report(state).errorAnalysis.join('')).toContain('杯底')
  })

  it('未完成四次称重不能保存一组数据', () => {
    const transition = controller.reduce(controller.createInitialState(), { type: 'recordTrial' })
    expect(transition.feedback.outcome).toBe('rejected')
    expect(transition.state.trials).toHaveLength(0)
  })

  it('保存后的组数据不随下一组、倒水和补水改变', () => {
    let state = finish(immersion(weighBaselines()))
    const saved = JSON.stringify(state.trials)
    state = act(state, 'newTrial')
    expect(state.samples.tension).toBe(null)
    expect(state.collectedVolume).toBe(0)
    expect(state.liquidVolume).toBe(90)
    expect(JSON.stringify(state.trials)).toBe(saved)
    expect(controller.restore(controller.snapshot(state))).toEqual(state)
    expect(controller.restore({ liquidVolume: NaN })).toEqual(controller.createInitialState())
  })

  it('撤销、重做和重置同时恢复液体量与器材状态', () => {
    let runtime = createLabRuntime(controller, weighBaselines())
    runtime = reduceLabAction(runtime, { type: 'move', payload: { subject: 'meter', position: { x: 195, y: 86 } } })
    runtime = reduceLabAction(runtime, { type: 'undo' })
    expect(runtime.present.collectedVolume).toBe(0)
    runtime = reduceLabAction(runtime, { type: 'redo' })
    expect(runtime.present.collectedVolume).toBeCloseTo(10)
    runtime = reduceLabAction(runtime, { type: 'reset' })
    expect(runtime.present).toEqual(controller.createInitialState())
  })

  it('一次连续拖动作为一个撤销步骤，保留轨迹产生的排液', () => {
    let runtime = createLabRuntime(controller, weighBaselines())
    runtime = reduceLabAction(runtime, { type: 'movePath', payload: { subject: 'meter', positions: [{ x: 195, y: -46 }, { x: 195, y: 86 }] } })
    expect(runtime.present.collectedVolume).toBeCloseTo(10)
    runtime = reduceLabAction(runtime, { type: 'undo' })
    expect(runtime.present.collectedVolume).toBe(0)
    expect(runtime.present.positions.meter).toEqual({ x: 474, y: 100 })
  })

  it('拖动过程中经过挂钩但未在挂钩处释放时，不会意外挂上器材', () => {
    const state = controller.reduce(controller.createInitialState(), { type: 'movePath', payload: { subject: 'object', positions: [{ x: 474, y: 334 }, { x: 550, y: 415 }] } }).state
    expect(state.attached).toBe(null)
    expect(state.positions.meter).toEqual({ x: 474, y: 100 })
  })

  it('记录液中示数后补水并额外排液，不能掩盖原先未加满的条件', () => {
    let state = act(weighBaselines(), 'setWaterVolume', 85)
    state = act(immersion(state), 'recordReading')
    state = act(state, 'detach')
    state = move(state, 'object', 474, 415)
    state = act(state, 'fill')
    // 再排出5mL，使累计收集量碰巧等于旧液中示数对应的10mL。
    state = move(state, 'object', 195, 256)
    state = move(state, 'object', 474, 415)
    state = move(state, 'meter', 474, 100)
    state = act(hang(state, 'bucket'), 'recordReading')
    state = act(state, 'recordTrial')
    expect(state.collectedVolume).toBeCloseTo(10)
    expect(state.trials[0].preparedVolume).toBe(85)
    expect(state.trials[0].valid).toBe(false)
    expect(controller.completion(state).complete).toBe(false)
  })

  it('旧桶液读数不能与后来新增的排液拼成有效数据组', () => {
    let state = move(weighBaselines(), 'meter', 195, -12.8)
    state = act(state, 'detach')
    state = move(state, 'meter', 474, 100)
    state = act(hang(state, 'bucket'), 'recordReading')
    expect(state.samples.filledBucketGravity).toBe(0.29)
    state = act(state, 'detach')
    state = move(state, 'bucket', 363, 378)
    state = hang(state, 'object')
    state = act(immersion(state), 'recordReading')
    state = act(state, 'recordTrial')
    expect(state.collectedVolume).toBeCloseTo(10)
    expect(state.trials[0].collectedVolume).toBeCloseTo(9)
    expect(state.trials[0].valid).toBe(false)
  })
})

describe('测力计设置与器材复位', () => {
  it('相同自重设置的四次称重仍有效；旧默认条件可迁移，缺失新条件不可被信任', () => {
    let state = act(controller.createInitialState(), 'setMeterSettings', { ...controller.createInitialState().meterSettings, ownWeight: true })
    state = act(hang(state, 'bucket'), 'recordReading')
    state = act(state, 'detach')
    state = move(state, 'bucket', 363, 378)
    state = act(hang(state, 'object'), 'recordReading')
    state = finish(immersion(state))
    expect(state.trials[0].valid).toBe(true)
    const unknown = JSON.parse(JSON.stringify(state))
    delete unknown.trials[0].sampleSettings
    expect(controller.restore(unknown).trials[0].valid).toBe(false)
    const legacy = JSON.parse(JSON.stringify(finish(immersion(weighBaselines()))))
    delete legacy.meterSettings
    delete legacy.sampleSettings
    delete legacy.trials[0].sampleSettings
    expect(controller.restore(legacy).trials[0].valid).toBe(true)
  })
  it('质量显示按质量精度记录并换算为牛顿，不沿用力显示的舍入', () => {
    let state = hang(controller.createInitialState(), 'object')
    state = act(state, 'setMeterSettings', { ...state.meterSettings, display: 'mass', decimals: 1 })
    state = act(state, 'recordReading')
    expect(state.samples.objectGravity).toBe(.88)
    expect(state.sampleSettings.objectGravity?.display).toBe('mass')
  })
  it('持续移动不挤占人工操作历史，撤销后停止，重做仍可恢复', () => {
    let runtime = createLabRuntime(controller)
    runtime = reduceLabAction(runtime, { type: 'setMeterSettings', payload: { ...runtime.present.meterSettings, speed: 20, lockMode: 'none' } })
    for (let i = 0; i < 40; i++) runtime = reduceLabAction(runtime, { type: 'advanceMeter', payload: .1 })
    expect(runtime.past).toHaveLength(1)
    runtime = reduceLabAction(runtime, { type: 'undo' })
    expect(runtime.present.meterSettings.speed).toBe(0)
    runtime = reduceLabAction(runtime, { type: 'redo' })
    expect(runtime.present.positions.meter.x).toBe(554)
    runtime = reduceLabAction(runtime, { type: 'move', payload: { subject: 'cup', position: { x: 220, y: 210 } } })
    runtime = reduceLabAction(runtime, { type: 'undo' })
    runtime = reduceLabAction(runtime, { type: 'advanceMeter', payload: .1 })
    expect(runtime.future).toHaveLength(1)
  })
  it.each(['object', 'bucket'] as const)('拖动悬挂的%s也遵守测力计方向锁', subject => {
    let state = hang(controller.createInitialState(), subject)
    state = act(state, 'setMeterSettings', { ...state.meterSettings, direction: 'left' })
    state = move(state, subject, 520, 470)
    expect(state.positions.meter).toEqual({ x: 474, y: 100 })
    state = move(state, subject, 450, 470)
    expect(state.positions.meter).toEqual({ x: 450, y: 100 })
  })
  it('四次称重混用自重条件时，即使差值相等也不能判定有效', () => {
    let state = act(hang(controller.createInitialState(), 'bucket'), 'recordReading')
    state = act(state, 'detach')
    state = act(state, 'setMeterSettings', { ...state.meterSettings, ownWeight: true })
    state = act(hang(state, 'object'), 'recordReading')
    state = act(state, 'setMeterSettings', { ...state.meterSettings, ownWeight: false })
    state = act(immersion(state), 'recordReading')
    state = act(state, 'detach')
    state = move(state, 'meter', 474, 100)
    state = act(state, 'setMeterSettings', { ...state.meterSettings, ownWeight: true })
    state = act(hang(state, 'bucket'), 'recordReading')
    state = act(state, 'recordTrial')
    expect(state.trials[0].valid).toBe(false)
    expect(controller.report(state).errorAnalysis.join('')).toContain('设置不一致')
    expect(controller.restore(controller.snapshot(state)).trials[0].valid).toBe(false)
  })
  it('仅复位摆位，保留排液、读数和设置，停止自动移动并恢复被删除的测力计', () => {
    let state = finish(immersion(weighBaselines()))
    state = act(state, 'setMeterSettings', { ...state.meterSettings, range: 10, speed: 20 })
    state = act(state, 'deleteMeter')
    const restored = act(state, 'resetLayout')
    expect(restored.positions).toEqual(controller.createInitialState().positions)
    expect(restored.collectedVolume).toBe(state.collectedVolume)
    expect(restored.liquidVolume).toBe(state.liquidVolume)
    expect(restored.trials).toEqual(state.trials)
    expect(restored.meterSettings.range).toBe(10)
    expect(restored.meterSettings.speed).toBe(0)
    expect(restored.meterRemoved).toBe(false)
    expect(restored.attached).toBeNull()
  })
  it('量程、下端自重与小数位实际影响读数，并可恢复旧快照', () => {
    let state = hang(controller.createInitialState(), 'object')
    state = act(state, 'setMeterSettings', { ...state.meterSettings, ownWeight: true, decimals: 1 })
    expect(readingsFor(state).force).toBeCloseTo(.931)
    state = act(state, 'recordReading')
    expect(state.samples.objectGravity).toBe(.9)
    const snapshot = controller.snapshot(state) as Record<string, unknown>
    delete snapshot.meterSettings
    expect(controller.restore(snapshot).meterSettings.range).toBe(5)
    expect(act(state, 'setMeterSettings', { ...state.meterSettings, range: 2 })).toEqual(state)
  })
  it('锁定吊环时只允许挂钩拉伸；锁定挂钩时上端移动而挂钩保持原位', () => {
    let state = controller.createInitialState()
    state = act(state, 'pullMeter', { endpoint: 'ring', position: { x: 474, y: 80 } })
    expect(state.positions.meter.y).toBe(100)
    state = act(state, 'pullMeter', { endpoint: 'hook', position: { x: 474, y: 346 } })
    expect(readingsFor(state).force).toBeCloseTo(1)
    expect(state.positions.meter.y).toBe(100)
    state = act(state, 'setMeterSettings', { ...state.meterSettings, lockMode: 'hook' })
    state = act(state, 'pullMeter', { endpoint: 'ring', position: { x: 474, y: 80 } })
    expect(state.positions.meter.y).toBe(80)
    expect(state.positions.meter.y + 220 + state.pullExtension).toBe(346)
  })
  it('方向锁定约束拖动，速度驱动持续移动，并保存轨迹', () => {
    let state = controller.createInitialState()
    state = act(state, 'setMeterSettings', { ...state.meterSettings, speed: 20, lockMode: 'none', direction: 'left', showTrace: true })
    state = act(state, 'advanceMeter', .5)
    expect(state.positions.meter).toEqual({ x: 464, y: 100 })
    expect(state.meterTrace.length).toBeGreaterThan(0)
    state = move(state, 'meter', 470, 110)
    expect(state.positions.meter).toEqual({ x: 464, y: 100 })
    expect(controller.restore(controller.snapshot(state))).toEqual(state)
  })
  it('开启弹性限度后，超量程损坏不能靠换量程或摆位复位掩盖', () => {
    let state = controller.createInitialState()
    state = act(state, 'setMeterSettings', { ...state.meterSettings, range: 1, elasticLimit: true })
    state = act(state, 'pullMeter', { endpoint: 'hook', position: { x: 474, y: 476 } })
    expect(state.meterDamaged).toBe(true)
    expect(controller.reduce(state, { type: 'recordReading' }).feedback.outcome).toBe('rejected')
    expect(act(state, 'resetLayout').meterDamaged).toBe(true)
    expect(controller.createInitialState().meterDamaged).toBe(false)
  })
})

describe('金属块设置', () => {
  it('满杯初次漂浮的沾水量按排液稳定后的6mL计算', () => {
    let state = hang(controller.createInitialState(), 'object')
    state = act(state, 'setObjectSettings', { material: 'wood', showScale: false, sway: false, wetting: true })
    state = immersion(state)
    state = move(state, 'meter', 474, 100)
    expect(state.objectWetVolume).toBeCloseTo(.3, 8)
    expect(state.liquidVolume + state.collectedVolume + state.objectWetVolume).toBeCloseTo(90)
  })
  it('漂浮不会带动已锁定方向的测力计，木块沾水按实际6mL浸入比例计算', () => {
    let state = immersion(weighBaselines())
    state = act(state, 'setMeterSettings', { ...state.meterSettings, direction: 'left' })
    state = act(state, 'setObjectSettings', { material: 'wood', showScale: false, sway: false, wetting: true })
    expect(state.positions.meter).toEqual({ x: 195, y: 86 })
    expect(readingsFor(state).submergedVolume).toBeCloseTo(6)
    state = act(state, 'detach')
    expect(readingsFor(state).submergedVolume).toBeCloseTo(6)
    expect(state.objectWetVolume).toBe(0)
    state = move(state, 'object', 474, 415)
    expect(state.objectWetVolume).toBeCloseTo(.3)
  })
  it('同体积切换铁块和铝块改变实际称重，保持排开体积', () => {
    let state = hang(controller.createInitialState(), 'object')
    state = act(state, 'setObjectSettings', { material: 'iron', showScale: false, sway: false, wetting: false })
    expect(readingsFor(state).force).toBeCloseTo(.7644)
    state = act(state, 'setObjectSettings', { ...state.objectSettings, material: 'aluminum' })
    expect(readingsFor(state).force).toBeCloseTo(.2646)
    state = immersion(state)
    expect(readingsFor(state).submergedVolume).toBeCloseTo(10)
    expect(readingsFor(state).force).toBeCloseTo(.1666)
  })
  it('木块不能被测力计向下压入水中，在水面漂浮并收集6mL排液', () => {
    let state = hang(controller.createInitialState(), 'object')
    state = act(state, 'setObjectSettings', { material: 'wood', showScale: false, sway: false, wetting: false })
    state = immersion(state)
    expect(readingsFor(state).submergedVolume).toBeCloseTo(6)
    expect(state.collectedVolume).toBeCloseTo(6)
    expect(readingsFor(state).force).toBeCloseTo(0)
  })
  it('删除悬挂块会卸载并停止排液；摆位复位保留设置和水量', () => {
    let state = immersion(weighBaselines())
    state = act(state, 'deleteObject')
    expect(state.objectRemoved).toBe(true)
    expect(state.attached).toBeNull()
    expect(readingsFor(state).submergedVolume).toBe(0)
    expect(readingsFor(state).force).toBe(0)
    const reset = act(state, 'resetLayout')
    expect(reset.objectRemoved).toBe(false)
    expect(reset.collectedVolume).toBe(state.collectedVolume)
    expect(controller.restore(controller.snapshot(reset))).toEqual(reset)
  })
  it('取出后沾水增加重量，重复浸入返还水滴并保持水量守恒', () => {
    let state = hang(controller.createInitialState(), 'object')
    state = act(state, 'setObjectSettings', { material: 'copper', showScale: false, sway: false, wetting: true })
    state = immersion(state)
    state = move(state, 'meter', 474, 100)
    expect(state.objectWetVolume).toBeCloseTo(.5)
    expect(readingsFor(state).force).toBeCloseTo(.8869)
    expect(state.liquidVolume + state.collectedVolume + state.lostVolume + state.objectWetVolume).toBeCloseTo(90)
    state = immersion(state)
    expect(state.objectWetVolume).toBe(0)
    expect(state.liquidVolume + state.collectedVolume + state.lostVolume).toBeCloseTo(90)
  })
  it('四次称重更换材质后不能混用，旧快照默认铜块且设置可保存', () => {
    let state = immersion(weighBaselines())
    state = act(state, 'setObjectSettings', { material: 'iron', showScale: true, sway: true, wetting: false })
    state = finish(state)
    expect(state.trials[0].valid).toBe(false)
    expect(controller.report(state).errorAnalysis.join('')).toContain('材质')
    expect(controller.restore(controller.snapshot(state))).toEqual(state)
    const snapshot = JSON.parse(JSON.stringify(controller.createInitialState()))
    delete snapshot.objectSettings
    expect(controller.restore(snapshot).objectSettings.material).toBe('copper')
  })
})

describe('接水小桶设置与删除', () => {
  it('锁定小桶阻止拖动；悬挂时也不能通过拖动测力计绕过锁定', () => {
    let state = act(controller.createInitialState(), 'setBucketLocked', true)
    state = move(state, 'bucket', 500, 400)
    expect(state.positions.bucket).toEqual({ x: 363, y: 378 })
    state = act(state, 'setBucketLocked', false)
    state = hang(state, 'bucket')
    state = act(state, 'setBucketLocked', true)
    state = move(state, 'meter', 500, 200)
    expect(state.positions.meter).toEqual({ x: 474, y: 100 })
    expect(state.positions.bucket).toEqual({ x: 474, y: 375 })
  })
  it('删除满桶卸载并记录排液损失，桶不再接水，复位可恢复', () => {
    let state = immersion(weighBaselines())
    state = act(state, 'detach')
    state = move(state, 'meter', 474, 100)
    state = hang(state, 'bucket')
    state = act(state, 'deleteBucket')
    expect(state.bucketRemoved).toBe(true)
    expect(state.attached).toBeNull()
    expect(readingsFor(state).force).toBe(0)
    expect(state.collectedVolume).toBe(0)
    expect(state.lostVolume).toBeCloseTo(10)
    state = move(state, 'object', 474, 415)
    state = act(state, 'fill')
    state = immersion(hang(state, 'object'))
    expect(state.collectedVolume).toBe(0)
    expect(state.lostVolume).toBeCloseTo(20)
    expect(state.liquidVolume + state.collectedVolume + state.lostVolume).toBeCloseTo(100)
    state = act(state, 'resetLayout')
    expect(state.bucketRemoved).toBe(false)
    expect(state.lostVolume).toBeCloseTo(20)
    expect(controller.restore(controller.snapshot(state))).toEqual(state)
  })
  it('锁定仍允许清空，清空降低悬挂桶示数且保留失水记录', () => {
    let state = act(immersion(weighBaselines()), 'detach')
    state = move(state, 'meter', 474, 100)
    state = hang(state, 'bucket')
    state = act(state, 'setBucketLocked', true)
    expect(readingsFor(state).force).toBeCloseTo(.298)
    state = act(state, 'emptyBucket')
    expect(readingsFor(state).force).toBeCloseTo(.2)
    expect(state.lostVolume).toBeCloseTo(10)
    expect(controller.restore(controller.snapshot(state)).bucketLocked).toBe(true)
  })
})

describe('溢水杯编辑、删除与杯底连接', () => {
  it('删除液中溢水杯取消浮力和杯底支持，水计入流失且复位不补水', () => {
    let state = immersion(weighBaselines())
    state = act(state, 'setCupName', '浮力实验杯')
    state = act(state, 'deleteCup')
    expect(state.cupRemoved).toBe(true)
    expect(readingsFor(state).submergedVolume).toBe(0)
    expect(readingsFor(state).bottomContact).toBe(false)
    expect(readingsFor(state).force).toBeCloseTo(.882)
    expect(state.liquidVolume).toBe(0)
    expect(state.collectedVolume).toBeCloseTo(10)
    expect(state.lostVolume).toBeCloseTo(80)
    expect(controller.reduce(state, { type: 'fill' }).feedback.outcome).toBe('rejected')
    expect(move(state, 'cup', 300, 100).positions.cup).toEqual({ x: 195, y: 210 })
    state = act(state, 'resetLayout')
    expect(state.cupRemoved).toBe(false)
    expect(state.cupName).toBe('浮力实验杯')
    expect(state.liquidVolume).toBe(0)
    expect(state.collectedVolume + state.lostVolume).toBeCloseTo(90)
  })
  it('杯底绳约束木块上浮，移动杯时连接物随动，解绳后恢复漂浮', () => {
    let state = act(controller.createInitialState(), 'setObjectSettings', { material: 'wood', showScale: false, sway: false, wetting: false })
    state = act(state, 'setCupTether', true)
    state = move(state, 'object', 195, 386)
    expect(state.cupTetherLength).toBeCloseTo(112)
    expect(state.attached).toBeNull()
    expect(readingsFor(state).submergedVolume).toBeCloseTo(10)
    expect(state.positions.object.y).toBe(386)
    state = move(state, 'object', 195, 100)
    expect(state.positions.object.y).toBe(386)
    state = move(state, 'cup', 205, 200)
    expect(state.positions.object).toEqual({ x: 205, y: 376 })
    expect(state.liquidVolume + state.collectedVolume + state.lostVolume).toBeCloseTo(90)
    expect(controller.restore(controller.snapshot(state))).toEqual(state)
    state = act(state, 'setCupTether', false)
    expect(state.cupTetherLength).toBeNull()
    expect(readingsFor(state).submergedVolume).toBeCloseTo(6)
  })
  it('沿杯底绳横向拖动不能伸长绳或穿过杯底', () => {
    let state = act(controller.createInitialState(), 'setCupTether', true)
    state = move(state, 'object', 195, 386)
    state = move(state, 'object', 500, 100)
    expect(state.positions.object.y + 78).toBeLessThanOrEqual(484)
    expect(state.positions.object.x).toBeCloseTo(258.8748777)
    expect(Math.hypot(state.positions.object.x - 195, 484 - state.positions.object.y + 14)).toBeCloseTo(112)
  })
  it('杯底连接与测力计悬挂互斥，删除后解开绳且沾水不会返还给不存在的杯', () => {
    let state = act(hang(controller.createInitialState(), 'object'), 'setCupTether', true)
    state = move(state, 'meter', 195, 86)
    expect(state.attached).toBeNull()
    expect(state.cupTetherLength).not.toBeNull()
    state = move(state, 'object', 474, 334)
    expect(state.attached).toBeNull()
    state = act(state, 'deleteCup')
    expect(state.cupTetherLength).toBeNull()
    state = act(hang(controller.createInitialState(), 'object'), 'setObjectSettings', { material: 'copper', showScale: false, sway: false, wetting: true })
    state = move(immersion(state), 'meter', 474, 100)
    expect(state.objectWetVolume).toBeCloseTo(.5)
    state = act(state, 'deleteCup')
    state = act(state, 'setObjectSettings', { ...state.objectSettings, wetting: false })
    expect(state.liquidVolume).toBe(0)
    expect(state.lostVolume + state.collectedVolume).toBeCloseTo(90)
    expect(controller.restore(controller.snapshot(state))).toEqual(state)
  })
  it('名称编辑、杯旁复位与删除可撤销，旧快照兼容且无效名称拒绝', () => {
    let runtime = createLabRuntime(controller)
    runtime = reduceLabAction(runtime, { type: 'setCupName', payload: '  自定义杯  ' })
    expect(runtime.present.cupName).toBe('自定义杯')
    runtime = reduceLabAction(runtime, { type: 'move', payload: { subject: 'cup', position: { x: 220, y: 180 } } })
    runtime = reduceLabAction(runtime, { type: 'resetCup' })
    expect(runtime.present.positions.cup).toEqual({ x: 220, y: 180 })
    expect(runtime.present.liquidVolume).toBe(90)
    runtime = reduceLabAction(runtime, { type: 'deleteCup' })
    runtime = reduceLabAction(runtime, { type: 'undo' })
    expect(runtime.present.cupRemoved).toBe(false)
    expect(runtime.present.liquidVolume).toBe(90)
    expect(controller.reduce(runtime.present, { type: 'setCupName', payload: ' ' }).feedback.outcome).toBe('rejected')
    const old = JSON.parse(JSON.stringify(runtime.present))
    delete old.cupName; delete old.cupRemoved; delete old.cupTether; delete old.cupTetherLength
    expect(controller.restore(old).cupName).toBe('溢水杯')
    expect(controller.restore(old).cupRemoved).toBe(false)
  })
})

describe('松手后器材重力与支撑', () => {
  it('倾倒清空逐渐减少真实水量，慢慢回正；水量守恒且动画不挤占撤销历史', () => {
    const state = { ...controller.createInitialState(), collectedVolume: 10, liquidVolume: 80 }
    let runtime = createLabRuntime(controller, state)
    runtime = reduceLabAction(runtime, { type: 'startBucketPour' })
    expect(runtime.present.collectedVolume).toBe(10)
    expect(runtime.present).toHaveProperty('bucketPour', { elapsed: 0, volume: 10 })
    for (let i = 0; i < 10; i++) runtime = reduceLabAction(runtime, { type: 'advanceBucketPour', payload: .1 })
    expect(runtime.present.collectedVolume).toBeGreaterThan(0)
    expect(runtime.present.collectedVolume).toBeLessThan(10)
    expect(runtime.present.liquidVolume + runtime.present.collectedVolume + runtime.present.lostVolume).toBeCloseTo(90)
    const restored = controller.restore(controller.snapshot(runtime.present))
    expect(restored).toEqual(runtime.present)
    for (let i = 0; i < 16; i++) runtime = reduceLabAction(runtime, { type: 'advanceBucketPour', payload: .1 })
    expect(runtime.present.collectedVolume).toBe(0)
    expect(runtime.present).toHaveProperty('bucketPour', null)
    expect(runtime.present.lostVolume).toBeCloseTo(10)
    expect(runtime.past).toHaveLength(1)
    expect(reduceLabAction(runtime, { type: 'undo' }).present).toEqual(state)
  })
  it('倾倒时不能重复清空、挂接、断开悬挂桶或采样；删除、复位停止动画且旧快照兼容', () => {
    let state = { ...hang(controller.createInitialState(), 'bucket'), collectedVolume: 10 }
    state = act(state, 'startBucketPour')
    expect(controller.reduce(state, { type: 'startBucketPour' }).feedback.outcome).toBe('rejected')
    expect(controller.reduce(state, { type: 'recordReading' }).feedback.outcome).toBe('rejected')
    expect(controller.reduce(state, { type: 'detach' }).feedback.outcome).toBe('rejected')
    expect(move(state, 'meter', 700, 0).positions).toEqual(state.positions)
    expect(act(state, 'resetLayout').bucketPour).toBeNull()
    expect(act(state, 'deleteBucket').bucketPour).toBeNull()
    const old = JSON.parse(JSON.stringify(controller.createInitialState()))
    delete old.bucketPour
    expect(controller.restore(old).bucketPour).toBeNull()
    let loose = { ...controller.createInitialState(), collectedVolume: 10 }
    loose = act(loose, 'startBucketPour')
    const y = loose.positions.bucket.y - 55 - 220
    expect(move(loose, 'meter', loose.positions.bucket.x, y).attached).toBeNull()
  })
  it.each(['object', 'bucket'] as const)('断开%s保留当前位置，加速落回桌面或地面，支持撤销和续落', subject => {
    for (const x of [474, 700]) {
      const hanging = move(hang(controller.createInitialState(), subject), 'meter', x, 50)
      let runtime = createLabRuntime(controller, hanging)
      runtime = reduceLabAction(runtime, { type: 'detach' })
      expect(runtime.present.attached).toBeNull()
      expect(runtime.present.positions[subject]).toEqual(hanging.positions[subject])
      expect(runtime.present.falling[subject]).toBe(0)
      runtime = reduceLabAction(runtime, { type: 'advanceGravity', payload: .1 })
      expect(runtime.present.positions[subject].y).toBeCloseTo(hanging.positions[subject].y + 5)
      expect(runtime.present.collectedVolume).toBe(hanging.collectedVolume)
      runtime = createLabRuntime(controller, controller.restore(controller.snapshot(runtime.present)))
      for (let i = 0; i < 100; i++) runtime = reduceLabAction(runtime, { type: 'advanceGravity', payload: 1 / 60 })
      expect(runtime.present.positions[subject]).toEqual({ x, y: subject === 'object' ? (x === 474 ? 415 : 636) : (x === 474 ? 378 : 602) })
      let undo = reduceLabAction(createLabRuntime(controller, hanging), { type: 'detach' })
      undo = reduceLabAction(undo, { type: 'advanceGravity', payload: .1 })
      expect(undo.past).toHaveLength(1)
      expect(reduceLabAction(undo, { type: 'undo' }).present).toEqual(hanging)
    }
  })
  it('断开采用摆动中的可见位置，下落保留桶内水且锁定桶不落下', () => {
    let state = hang(controller.createInitialState(), 'bucket')
    state = { ...state, collectedVolume: 10 }
    state = act(state, 'detach', { position: { x: 500, y: 330 } })
    expect(state.positions.bucket).toEqual({ x: 500, y: 330 })
    expect(state.falling.bucket).toBe(0)
    for (let i = 0; i < 100; i++) state = act(state, 'advanceGravity', 1 / 60)
    expect(state.positions.bucket.y).toBe(378)
    expect(state.collectedVolume).toBe(10)
    const locked = act(hang(controller.createInitialState(), 'bucket'), 'setBucketLocked', true)
    expect(act(locked, 'detach').positions.bucket).toEqual(locked.positions.bucket)
    expect(act(locked, 'detach').falling.bucket).toBeUndefined()
  })
  function drop(state: ArchimedesState, subject: string, x: number, y: number) {
    return act(state, 'dropPath', { subject, positions: [{ x, y }] })
  }
  function land(state: ArchimedesState) {
    for (let i = 0; i < 180; i++) state = act(state, 'advanceGravity', 1 / 60)
    return state
  }
  it.each([['object', 415, 636], ['bucket', 378, 602], ['cup', 210, 434]] as const)('%s移出桌面后加速下落并停在地面', (subject, startY, groundY) => {
    let state = drop(controller.createInitialState(), subject, 700, startY)
    expect(state.falling[subject]).toBe(0)
    state = act(state, 'advanceGravity', .1)
    expect(state.positions[subject].y).toBeCloseTo(startY + 5)
    expect(state.falling[subject]).toBeCloseTo(100)
    state = land(state)
    expect(state.positions[subject]).toEqual({ x: 700, y: groundY })
    expect(state.falling).toEqual({})
    expect(state.liquidVolume + state.collectedVolume + state.lostVolume + state.objectWetVolume).toBeCloseTo(90)
    expect(controller.restore(controller.snapshot(state))).toEqual(state)
  })
  it('桌面上方落回桌面，桌面下方落地；杯内铜块沉底、木块仍漂浮', () => {
    let state = land(drop(controller.createInitialState(), 'object', 474, 200))
    expect(state.positions.object.y).toBe(415)
    state = land(drop(state, 'object', 474, 550))
    expect(state.positions.object.y).toBe(636)
    state = land(drop(controller.createInitialState(), 'object', 195, 636))
    expect(readingsFor(state).submergedVolume).toBe(0)
    expect(readingsFor(state).bottomContact).toBe(false)
    state = land(drop(controller.createInitialState(), 'object', 195, 320))
    expect(state.positions.object.y).toBe(406)
    expect(readingsFor(state).bottomContact).toBe(true)
    state = act(controller.createInitialState(), 'setObjectSettings', { material: 'wood', showScale: false, sway: false, wetting: false })
    state = land(drop(state, 'object', 195, 386))
    expect(readingsFor(state).submergedVolume).toBeCloseTo(6)
  })
  it('悬挂器材和锁定小桶不落下，杯底连接随杯落地且不穿底', () => {
    let state = drop(hang(controller.createInitialState(), 'object'), 'meter', 700, 100)
    expect(land(state).positions.object).toEqual({ x: 700, y: 400 })
    state = act(controller.createInitialState(), 'setBucketLocked', true)
    state = drop(state, 'bucket', 700, 200)
    expect(land(state).positions.bucket).toEqual({ x: 363, y: 378 })
    state = act(controller.createInitialState(), 'setCupTether', true)
    state = move(state, 'object', 195, 386)
    state = land(drop(state, 'cup', 700, 210))
    expect(state.positions.cup.y).toBe(434)
    expect(state.positions.object.y + 78).toBeLessThanOrEqual(708)
    expect(state.positions.object.x).toBe(700)
    expect(state.liquidVolume + state.collectedVolume + state.lostVolume).toBeCloseTo(90)
  })
  it('下落自动推进不污染撤销，刷新续落，复位和删除停止原下落', () => {
    let runtime = createLabRuntime(controller)
    runtime = reduceLabAction(runtime, { type: 'dropPath', payload: { subject: 'object', positions: [{ x: 700, y: 415 }] } })
    runtime = reduceLabAction(runtime, { type: 'advanceGravity', payload: .1 })
    expect(runtime.past).toHaveLength(1)
    expect(controller.restore(controller.snapshot(runtime.present)).falling.object).toBe(100)
    runtime = reduceLabAction(runtime, { type: 'undo' })
    expect(runtime.present.positions.object).toEqual({ x: 474, y: 415 })
    expect(runtime.present.falling).toEqual({})
    runtime = reduceLabAction(runtime, { type: 'redo' })
    runtime = reduceLabAction(runtime, { type: 'resetLayout' })
    expect(runtime.present.falling).toEqual({})
    let state = drop(controller.createInitialState(), 'cup', 700, 210)
    state = act(state, 'deleteCup')
    expect(state.falling.cup).toBeUndefined()
    expect(controller.restore(controller.snapshot(state))).toEqual(state)
    const old = JSON.parse(JSON.stringify(controller.createInitialState()))
    delete old.falling
    expect(controller.restore(old).falling).toEqual({})
  })
})
